export const ARTICLE_DELETE = 'ARTICLE_DELETE';
export const ARTICLE_SET_OPEN = 'ARTICLE_SET_OPEN';
export const ARTICLE_SET_CREATE = 'ARTICLE_SET_CREATE';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_POSTS_INFO = 'SET_POSTS_INFO';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const RESET_DATA_FROM_SERVER = 'RESET_DATA_FROM_SERVER';
 